/*
fn testFN =
(
	print "toto"
)

myScriptPath = getINISetting  "G:/Users/nico/AppData/Local/Autodesk/3dsMax/2015 - 64bit/ENU/Plugin.UserSettings.ini" "Directories" "MyMaxScripts"
print var

test = #(1,2,3)
-- print test
var = test.count
*/

/*
--à partir de trois bones
os = $selection as array
if os.count == 3 do print "ok! good selection."

-- création de bak bones
BakBonesFN (os)
*/

-- print $.scale.controller.

print "tutu"