-- HOW TO

-- "ControlPanelLauncher.ms" appelle "controlStackHelper.ms" genere le macroscript

-- "controlStackHelper.ms" appelle "controlPanel.ms"

-- "controlPanel.ms" appelle "button_fonction.ms"
-- "controlPanel.ms" appelle "button_placer_UI.ms"

-- "controlPanel.ms" utilise  "button_placer_UI.ms" pour générer la prévu avec les bouton
-- "controlPanel.ms" genere "setButtonTemp.ms" à la racine du fichier max
-- "controlPanel.ms" genere le fichier final à la racine du fichier max